# Generated by Django 5.2.5 on 2025-08-26 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Nacionalidad', models.CharField(max_length=50)),
                ('Fecha_Nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Fecha_Publicacion', models.DateField()),
                ('Numero_Paginas', models.PositiveIntegerField()),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='app_unidad2.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=150)),
                ('Direccion', models.CharField(max_length=200)),
                ('Pais', models.CharField(max_length=50)),
                ('Libros', models.ManyToManyField(related_name='editoriales', to='app_unidad2.libro')),
            ],
        ),
    ]
